#!/usr/bin/env bash

scripts/update_defconfig alioth
echo "Regenerate cat_defconfig ..."
mkdir out || exit 0
make alioth_defconfig O=out || exit 0
mv out/.config arch/arm64/configs/cat_defconfig || exit 0
rm -rf out
echo "Commiting ..."
git add arch/arm64/configs/cat_defconfig
git commit -sm "cat_defconfig: update"